// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RightMove.EF;

#nullable disable

namespace RightMove.EF.Migrations
{
    [DbContext(typeof(RightMoveContext))]
    partial class RightMoveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("RightMove.Db.Entities.ResultsTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResultsTable");
                });

            modelBuilder.Entity("RightMove.Db.Entities.RightMoveProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateReduced")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dates")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultsTableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightMoveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResultsTableId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("RightMove.Db.Entities.RightMoveProperty", b =>
                {
                    b.HasOne("RightMove.Db.Entities.ResultsTable", "ResultsTable")
                        .WithMany("Properties")
                        .HasForeignKey("ResultsTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultsTable");
                });

            modelBuilder.Entity("RightMove.Db.Entities.ResultsTable", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
