// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RightMove.EF;

#nullable disable

namespace RightMove.EF.Migrations
{
    [DbContext(typeof(RightMoveContext))]
    partial class RightMoveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RightMove.Db.Entities.ResultsTable", b =>
                {
                    b.Property<int>("ResultsTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultsTableId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResultsTableId");

                    b.ToTable("ResultsTable");
                });

            modelBuilder.Entity("RightMove.Db.Entities.RightMoveProperty", b =>
                {
                    b.Property<int>("RightMovePropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RightMovePropertyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReduced")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResultsTableId")
                        .HasColumnType("int");

                    b.Property<int>("RightMoveId")
                        .HasColumnType("int");

                    b.HasKey("RightMovePropertyId");

                    b.HasIndex("ResultsTableId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("RightMove.Db.Entities.RightMoveProperty", b =>
                {
                    b.HasOne("RightMove.Db.Entities.ResultsTable", "ResultsTable")
                        .WithMany("Properties")
                        .HasForeignKey("ResultsTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultsTable");
                });

            modelBuilder.Entity("RightMove.Db.Entities.ResultsTable", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
