// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RightMove.Db;

#nullable disable

namespace RightMove.Db.Migrations
{
    [DbContext(typeof(RightMoveContext))]
    [Migration("20231214235930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RightMove.Db.Entities.ResultsTable", b =>
                {
                    b.Property<int>("ResultsTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("ResultsTableId");

                    b.ToTable("ResultsTable");
                });

            modelBuilder.Entity("RightMove.Db.Entities.RightMovePropertyEntity", b =>
                {
                    b.Property<int>("RightMovePropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateReduced")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dates")
                        .HasColumnType("longtext");

                    b.Property<string>("HouseInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("Prices")
                        .HasColumnType("longtext");

                    b.Property<int>("ResultsTableId")
                        .HasColumnType("int");

                    b.Property<int>("RightMoveId")
                        .HasColumnType("int");

                    b.HasKey("RightMovePropertyId");

                    b.HasIndex("ResultsTableId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("RightMove.Db.Entities.RightMovePropertyEntity", b =>
                {
                    b.HasOne("RightMove.Db.Entities.ResultsTable", "ResultsTable")
                        .WithMany("Properties")
                        .HasForeignKey("ResultsTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultsTable");
                });

            modelBuilder.Entity("RightMove.Db.Entities.ResultsTable", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
