// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RightMove.Db;

#nullable disable

namespace RightMove.Db.Migrations
{
    [DbContext(typeof(RightMoveContext))]
    partial class RightMoveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RightMove.Db.Entities.DatePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int?>("RightMovePropertyEntityRightMovePropertyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RightMovePropertyEntityRightMovePropertyId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("RightMove.Db.Entities.ResultsTable", b =>
                {
                    b.Property<int>("ResultsTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResultsTableId"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ResultsTableId");

                    b.ToTable("ResultsTable");
                });

            modelBuilder.Entity("RightMove.Db.Entities.RightMovePropertyEntity", b =>
                {
                    b.Property<int>("RightMovePropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RightMovePropertyId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateReduced")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HouseInfo")
                        .HasColumnType("text");

                    b.Property<int>("ResultsTableId")
                        .HasColumnType("integer");

                    b.Property<int>("RightMoveId")
                        .HasColumnType("integer");

                    b.HasKey("RightMovePropertyId");

                    b.HasIndex("ResultsTableId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("RightMove.Db.Entities.DatePrice", b =>
                {
                    b.HasOne("RightMove.Db.Entities.RightMovePropertyEntity", null)
                        .WithMany("Prices")
                        .HasForeignKey("RightMovePropertyEntityRightMovePropertyId");
                });

            modelBuilder.Entity("RightMove.Db.Entities.RightMovePropertyEntity", b =>
                {
                    b.HasOne("RightMove.Db.Entities.ResultsTable", "ResultsTable")
                        .WithMany("Properties")
                        .HasForeignKey("ResultsTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultsTable");
                });

            modelBuilder.Entity("RightMove.Db.Entities.ResultsTable", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RightMove.Db.Entities.RightMovePropertyEntity", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
